name: sass_builder_example
description: Example to build .css files from .scss source.
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  bootstrap_sass: ^4.5.0
dev_dependencies:
  build_runner: '^2.0.0'
  build_web_compilers: ^3.0.0
  lints: ^2.0.0
  sass_builder:
    path: ../
