name: sass_builder
version: 2.2.1

homepage: https://github.com/dart-league/sass_builder
description: Transpile sass files using the "build" package.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: ^2.4.0
  build_config: ^1.1.0
  path: ^1.8.0
  sass: ^1.62.0

dev_dependencies:
  build_test: ^2.1.0
  lints: ^2.1.0
  test: ^1.24.0
  source_maps: ^0.10.12
