name: Dart CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

env:
  PUB_ENVIRONMENT: bot.github
  PUB_CACHE: ".dart_tool/pub_cache"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
      # We can remove --no-example once the bootstrap issue has been resolved
        run: dart pub upgrade --no-example

      - name: Ensure format
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project
        run: dart analyze --fatal-infos

      - name: Run tests
        run: dart test

# Currently broken due to https://github.com/dart-league/bootstrap_sass/issues/12
#      - name: Ensure example builds
#        working-directory: example
#        run: dart run build_runner build
